---
title: "UB01A3"
author: "Anatol"
date: "3/20/2022"
output:
  html_document:
    code_folding: hide
    df_print: kable
    fig_caption: yes
    fig_height: 5
    fig_width: 5
    theme: united
    self_contained: yes
    toc: yes
    toc_float: yes
    toc_level: 3
---

```{r, include = FALSE}
library(dplyr)
library(magrittr)
library(flair)
library(pipeR)
library(knitr)
library(rmarkdown)
library(shiny)
library(shinyWidgets)
library(arm)
library(rAmCharts)
library(xfun)
colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color, 
      x)
  } else x
}

xfun::pkg_load2(c("htmltools", "mime"))
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo=FALSE}
.description {
  color: gray;
  font-style: italics;
```
# Aufgabe 3: Mehrfachregression  

```{r}
states <- as.data.frame(state.x77)
head(states)
str(states)
summary(states)

```


## 3a)
*Passen Sie zunachst das volle Modell an, d.h. regressieren Sie Life.Exp auf alle im Datensatz vorhandenen restlichen Variablen. Vermeiden Sie bitte den Befehlattach. Wie hoch ist das Bestimmtheitsmaß und das
adjustierte Bestimmtheitsmaß?*

```{r}
multLinRegFull <- lm (`Life Exp` ~ ., data = states)
summary(multLinRegFull)
```

Bestimmtheitsmaß betragt 0.7362; das adjustierte Bestimmtheitsmaß 0.6922 

